# Generated by Django 2.2.10 on 2021-06-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001__initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='',
        ),
    ]
