# Generated by Django 2.2.10 on 2021-06-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_contect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contect',
            old_name='name_first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contect',
            old_name='name_last',
            new_name='last_name',
        ),
    ]
